name: New Feature
description: Request a New feature
title: "[Feature]: "
labels: [new Feature]
assignees:
  - warhammer4000
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What do you wish to add?
      description: Please describe
    validations:
      required: true

- type: textarea
    id: solution
    attributes:
      label: Proposed Solution 
      description: Please describe
    validations:
      required: true

- type: textarea
    id: workaround
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
