name: Publish Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Get Version from Tag
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }}
    - name: Publish DTD.Sort.Net
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: ./DTD.Sort.Net.Main/DTD.Sort.Net.Main.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.get_version.outputs.version-without-v }}
