name: Raptor Nuget Packages
  
on: 
   release:
    types: [published, created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Version from Tag
      id: get_version
      uses: battila7/get-version-action@v2
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }} 
    - name: Push with dotnet
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  
