name: publish to nuget
on:
   release:
    types:
      - published
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
    
    - name: Get tag
      id: get_version
      uses: battila7/get-version-action@v2
      
    - run: dotnet build
    - name: Create the package
      run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

    - name: Publish the package to nuget.org
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
